name: Deploy Docusaurus to GitHub Pages

on:
  push:
    branches:
      - main  # Varsayılan dalınıza göre burayı değiştirin

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Setup Node.js (Specify Node.js version if needed)
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Projeye bağlı olarak Node.js sürümünü güncelleyin

    - name: Install Dependencies and Build
      run: |
        cd website
        npm install
        npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./frame-design-systemm/website/build
        keep_files: false  # Önceki deploylardan dosyaları korumak istemiyorsanız false yapın, istiyorsanız true